#!/bin/bash

filename=main.xml
basename=${filename%\.*}

do_eval=1
do_pdf=1
do_man=1
do_html=1

make_dir (){
    if [ $# -ne 1 ]; then
	echo You have to give a directory name.
	exit 1
    fi

    dirname=$1

    if [ -d $dirname ]; then
        if [ -d $dirname.junk ]; then
            rm -rf $dirname.junk
        fi

        mv -f $dirname $dirname.junk
    fi

    mkdir $dirname
}

if [ $do_eval ]; then
    echo Validating...

    db2x.sh -o -W $filename
fi

if [ $do_pdf ]; then
    echo Creating PDF...

    texfile=$basename.tex
    make_dir pdf
    cd pdf
    db2tex -o -s ../docu.dsl ../$filename
    mv ../$texfile .

    pdfjadetex "$texfile"

    # if there are unresolved references, re-run pdfjadetex, twice
    if egrep '^LaTeX Warning: There were undefined references.$' $basename.log >/dev/null 2>&1
	then
	    pdfjadetex "$texfile"
	    pdfjadetex "$texfile"
    fi
    cd ..
fi

if [ $do_man ]; then
    echo Creating manuals...

    make_dir man
    cd man
    docbook2manxml --header-3="`date "+%d %B %Y"`" --header-5="ParaStation" \
		--noxref-on-link ../$filename > $basename.mxml || \
    docbook2manxml --header-3="`date "+%d %B %Y"`" --header-5="ParaStation" \
		--noxref-on-link ../$filename > $basename.mxml
    db2x_manxml $basename.mxml
    cd ..
fi

if [ $do_html ]; then
    echo Creating HTML...

    db2html -o -s docu.dsl $filename

    make_dir html
    rmdir html
    mv $basename html
    cd html
    for i in *.html; do
	tidy -m -f /dev/null -asxml $i
    done
    cd ..
fi
