#!/bin/bash

filename=main.xml
basename=${filename%\.*}

export SGML_CATALOG="/var/lib/sgml/CATALOG.db42xml"

xsltcommand="xsltproc --catalogs --timing --nonet"

do_eval=1
# do_pdf=1
do_oldpdf=1
do_man=1
do_html=1

make_dir (){
    if [ $# -ne 1 ]; then
	echo You have to give a directory name.
	exit 1
    fi

    dirname=$1

    if [ -d $dirname ]; then
        if [ -d $dirname.junk ]; then
            rm -rf $dirname.junk
        fi

        mv -f $dirname $dirname.junk
    fi

    mkdir $dirname
}

if [ $do_eval ]; then
    echo Validating...

    db2x.sh -o -W $filename
fi

if [ $do_oldpdf ]; then
    echo Creating PDF...

    texfile=$basename.tex
    make_dir pdf
    cd pdf
    db2tex -o -s ../docu.dsl ../$filename
    mv ../$texfile .

    pdfjadetex "$texfile"

    # if there are unresolved references, re-run pdfjadetex, twice
    if egrep '^LaTeX Warning: There were undefined references.$' $basename.log >/dev/null 2>&1
	then
	    pdfjadetex "$texfile"
	    pdfjadetex "$texfile"
    fi
    cd ..
fi

if [ $do_pdf ]; then
    echo Creating PDF...

    fofile=$basename.fo
    make_dir pdf
    cd pdf
    $xsltcommand -o $fofile ../StyleSheets/fo.xsl ../main.xml

    # this does actually *not* work
    pdfxmltex $fofile

    cd ..
fi

if [ $do_man ]; then
    echo Creating manuals...

    make_dir man
    cd man
    
#    export CLASSPATH=/usr/lib/saxon/saxon.jar

    $xsltcommand ../StyleSheets/db2man.xsl ../main.xml
#    java com.icl.saxon.StyleSheet ../main.xml ../StyleSheets/db2man.xsl
    cd ..
fi

if [ $do_html ]; then
    echo Creating HTML...

    make_dir html
    cd html
#    export CLASSPATH=/usr/lib/saxon/saxon.jar

#    java com.icl.saxon.StyleSheet ../main.xml ../StyleSheets/html.xsl
    $xsltcommand ../StyleSheets/html.xsl ../main.xml
#    for i in *.html; do
#	tidy -m -f /dev/null -asxml $i
#    done
    cd ..
fi
