#!/usr/bin/env python
#
#               ParaStation psmom test suite
#
# Copyright (C) 2011 ParTec Cluster Competence Center GmbH, Munich
#
# author
# Michael Rauh (rauh@par-tec.com)
#

import os, sys
from stat import *

sys.path.append(os.getenv("RTH"))
from rth import *

r = rth()
ofile = os.getenv("OUTPUT_FILE")
efile = os.getenv("ERROR_FILE")

rth.parseOutput(r, ofile)
rth.testEnv(r, "UMASK", os.getenv("UMASK"))


# test permissions of output file
sinfo = os.stat(ofile)
if sinfo == -1:
    print("invalid output file '" + ofile + "'")

mask = oct((S_IRWXU | S_IRWXG | S_IRWXO) & sinfo.st_mode)
expect_mask = oct(0o644)

if mask != expect_mask:
    print("invalid permissions '" + str(mask) + "' for output file '" + ofile \
            + "' should be '" + str(expect_mask) + "'")


# test permissions of error file
sinfo = os.stat(efile)
if sinfo == -1:
    print("invalid error file '" + efile + "'")

mask = oct((S_IRWXU | S_IRWXG | S_IRWXO) & sinfo.st_mode)
expect_mask = oct(0o644)

if mask != expect_mask:
    print("invalid permissions '" + str(mask) + "' for error file '" + efile \
            + "' should be '" + str(expect_mask) + "'")
