#!/usr/bin/perl
#
# ParaStation
#
# Copyright (C) 2008 ParTec Cluster Competence Center GmbH, Munich
#
# This file may be distributed under the terms of the Q Public License
# as defined in the file LICENSE.QPL included in the packaging of this
# file.
#
# This script starts some test programs as fast as possible and does
# some timing measurements.
#

$maxNP=52;

$numStartup=3;

$numMeasure=20;

if (exists($ENV{"USE_MPI1"})) {
    $mpi_starter="/opt/parastation/mpich/bin/mpirun";
    $mpi_prog="mpi_startup.1";
    $resultFile="results.1";
} else {
    $mpi_starter="mpiexec";
    $mpi_prog="mpi_startup.2";
    $resultFile="results.2";
}
$timer="/usr/bin/time -f %e";

$ENV{PSI_NOMSGLOGGERDONE} = "";

open(RES, ">", $resultFile);

for ($np=1; $np <= $maxNP; $np++) {
    $sum=0;
    $ssum=0;

    for ($i=0 ; $i<$numStartup; $i++) {
	system("${mpi_starter} -np ${np} ${mpi_prog} 2>&1 > /dev/null");
    }

    for ($i=0; $i<$numMeasure; $i++) {
	$val=`${timer} ${mpi_starter} -np ${np} ${mpi_prog} 2>&1 > /dev/null`;
	$sum+=$val;
	$ssum+=$val*$val;
    }

    $t = $sum/$numMeasure;
    $tmp = $ssum/$numMeasure - $t*$t;
    if ($tmp < 0) {
	print "Warning: tmp ", $tmp, " less than 0\n";
	$tmp=0.0;
    }
    $dt=sqrt($tmp);

    print $np, "\t", $t, "\t", $dt, "\n";
    print RES $np, "\t", $t, "\t", $dt, "\n";
}

close(RES);
