#!/bin/bash
#
# ParaStation
#
# Copyright (C) 2008 ParTec Cluster Competence Center GmbH, Munich
#
# This file may be distributed under the terms of the Q Public License
# as defined in the file LICENSE.QPL included in the packaging of this
# file.
#
# Script to orchestrate various stress testing scripts
#

if [ -f stopIt ]; then
    echo \'stopIt\' exists -- starting prohibited
    exit 1
fi

log=log.`hostname`
exec 8> $log
echo "log to $log"

if [ ! -s config ]; then
    echo "No configuration file ('config') found"
    exit 1
fi

. config

for node in ${nodeList}; do
    envName="envStr_"${node}
    cmd='cd '`pwd`'; su '${user}' -c "env '${envStr}' '${!envName}
    cmd=${cmd}' ./stressTester"'

    ssh ${node} ${cmd} >&8 &
done

for node in ${killerList}; do
    ssh ${node} 'cd '`pwd`'; ./psidKiller '${disabled:-30}' '${sleep:-60} >&8 &
done

while true; do

    if [ -f stopIt ]; then
	echo `date` Stopping >&8
	exit 0
    fi

    sleep 30

done
