#!/bin/bash

[ -z "$PSGWD_BINARY" ] && {
    echo "ERROR: missing PSGWD_BINARY"
    exit 1
}

[ -x "$PSGWD_BINARY" ] || {
    echo "ERROR: $PSGWD_BINARY is not executable"
    exit 1
}

[ -n "$SLURM_SPANK_PSGW_ENV" ] && {
  set -a; eval "$SLURM_SPANK_PSGW_ENV"
  unset SLURM_SPANK_PSGW_ENV; set +a
}

exec $PSGWD_BINARY --showpid --any --daemonize --user $PSGWD_UID $SLURM_SPANK_PSGW_ARGS 0</dev/null
