#!/bin/bash

[ -z "$PSGWD_PID" ] && {
    echo "ERROR: missing PSGWD_PID"
    exit 1
}

[ -z "$PSGWD_UID" ] && {
    echo "ERROR: missing PSGWD_UID"
    exit 1
}

REAL_UID=$(ps -p $PSGWD_PID -o euid |grep -v "EUID" | tr -d '[:space:]')
[ "$REAL_UID" != "$PSGWD_UID" ] && {
    echo "ERROR: psgwd using UID '$REAL_UID' not '$PSGWD_UID'"
    exit 1
}

[ -z "$PSGWD_USER" ] && {
    echo "ERROR: missing PSGWD_USER"
    kill -9 "$PSGWD_PID"
    exit 0;
}

su -c 'kill -9 "-$PSGWD_PID"' $PSGWD_USER
