#!/bin/sh


if [ ! -f .ROOTDIR ] ;then
    echo Please call $0 from psmlib Rootdir
    exit 1;
fi

dest=${1:?"use $0 <destdir>"}

touch $dest/.ROOTDIR
cp -au Makefile.include $dest
cp -au lib $dest
cp -au modules $dest
cp -au include $dest
cp -au tools $dest

