#!/bin/sh

#first build all
make clean
make KDIR=/home/i41pc17/hauke/psmlib/kernel/i386/linux-2.2.16.SuSE  OSSUF=.SuSE all

#and now the modules
make KDIR=/home/i41pc17/hauke/psmlib/kernel/i386/linux-2.2.16.SuSE  OSSUF=.SuSE psm
make KDIR=/home/i41pc17/hauke/psmlib/kernel/i386/linux-2.2.16-SMP.SuSE  OSSUF=.SuSE psm

make KDIR=/home/i41pc17/hauke/psmlib/kernel/i386/linux-2.2.18.SuSE  OSSUF=.SuSE psm
make KDIR=/home/i41pc17/hauke/psmlib/kernel/i386/linux-2.2.18-SMP.SuSE  OSSUF=.SuSE psm


make KDIR=/home/i41pc17/hauke/psmlib/kernel/i386/linux-2.4.2.SuSE LINUXVERSION=L24 OSSUF=.SuSE psm
make KDIR=/home/i41pc17/hauke/psmlib/kernel/i386/linux-2.4.2-SMP.SuSE LINUXVERSION=L24 OSSUF=.SuSE psm

#make KDIR=/home/i41pc17/hauke/psmlib/kernel/i386/linux-2.4.2.redhat LINUXVERSION=L24 OSVER=2.4.2-2 OSSUF=.redhat psm
make KDIR=/home/i41pc17/hauke/psmlib/kernel/i386/linux-2.4.2-SMP.redhat LINUXVERSION=L24 OSVER=2.4.2-2smp OSSUF=.redhat psm

make KDIR=/home/i41pc17/hauke/psmlib/kernel/i386/linux-2.4.2 LINUXVERSION=L24 OSSUF=  psm
make KDIR=/home/i41pc17/hauke/psmlib/kernel/i386/linux-2.4.2-SMP LINUXVERSION=L24 OSSUF=-SMP psm

make KDIR=/home/i41pc17/hauke/psmlib/kernel/i386/linux-2.4.9 LINUXVERSION=L24 OSSUF=  psm
make KDIR=/home/i41pc17/hauke/psmlib/kernel/i386/linux-2.4.9-SMP LINUXVERSION=L24 OSSUF=-SMP psm
