#!/bin/bash

if [ $# -ne 1 ]; then
    echo Usage: ${0} \<np\>
    exit 1
fi

np=${1}

export PSP_DEBUG=0
unset PSI_LOOP_NODES_FIRST
export PSI_WAIT=1

log=log.`hostname`
exec 8> $log 
echo "log to $log"


i=0
while true; do

    if [ -f stopIt ]; then
	echo `date` Stopping after $i >&8
	exit 0
    fi

    mpiexec -np ${np} mpi_hello 2>&1 | \
	grep -E -v '(Hello World from )|(Hi from rank)' | \
	grep -E -v '(PSIlogger: done)|(^$)' >&8

    if ((i%1000==0)); then
	echo `date`  $i >&8
    fi

    ((i++));
done

