#!/bin/bash

export PSP_DEBUG=0
unset PSI_LOOP_NODES_FIRST
export PSI_WAIT=1

log=log.`hostname`
exec 8> $log 
echo "log to $log"


i=0
while true; do

mpiexec -np 15 mpi_hello 2>&1 | \
    grep -E -v '(Hello World from )|(Hi from rank)|(PSIlogger: done)|(^$)' >&8

if ((i%1000==0)); then
    echo `date`  $i >&8
fi

((i++));

 
done

