#!/bin/bash

log=log.`hostname`
exec 8> $log 
echo "log to $log"

. config

cmd='cd '`pwd`'; su '${user}' -c "env '${envStr}' ./stressTester '${num:-1}'"'

for node in ${nodeList}; do
    ssh ${node} ${cmd} >&8 &
done

for node in ${killerList}; do
    ssh ${node} 'cd '`pwd`'; ./psidKiller '${disabled:-30}' '${sleep:-60} >&8 &
done

while true; do

    if [ -f stopIt ]; then
	echo `date` Stopping >&8
	exit 0
    fi

    sleep 30

done