#!/bin/bash
#
# Copyright (c) 2008 ParTec Cluster Competence Center GmbH, Munich
# All rights reserved.
#
# Script to orchestrate various stress testing scripts
#
# Author: Norbert Eicker <eicker@par-tec.com>
#
# $Id$
#

log=log.`hostname`
exec 8> $log 
echo "log to $log"

. config


for node in ${nodeList}; do
    envName="envStr_"${node}
    cmd='cd '`pwd`'; su '${user}' -c "env '${envStr}' '${!envName}
    cmd=${cmd}' ./stressTester"'

    ssh ${node} ${cmd} >&8 &
done

for node in ${killerList}; do
    ssh ${node} 'cd '`pwd`'; ./psidKiller '${disabled:-30}' '${sleep:-60} >&8 &
done

while true; do

    if [ -f stopIt ]; then
	echo `date` Stopping >&8
	exit 0
    fi

    sleep 30

done