#!/bin/sh
# esub for lsf
#######################################################################

if [ -z "$LSB_SUB_PARM_FILE" ]; then
    # if not set do nothing
    exit 0
fi

. $LSB_SUB_PARM_FILE

# Redirect stderr to stdout so echo can be used for error
exec 1>&2

# Assume
PSM_ADDITIONAL_KEY="mpich_psm"
PJL_WRAPPER="psm_lsf_wrapper"
PSM_ADDITIONAL_CMD="pam -g 1 $PJL_WRAPPER"

ttt=`echo $LSB_SUB_ADDITIONAL | grep -i "$PSM_ADDITIONAL_KEY"`
if [ -z "$ttt" ]; then
	# if no -a mpich_psm is specified then do nothing
	exit 0;
fi

echo "LSB_SUB_COMMAND_LINE=\"$PSM_ADDITIONAL_CMD $LSB_SUB_COMMAND_LINE"\" >> $LSB_SUB_MODIFY_FILE

# useful for debugging purposes
#echo "LSB_SUB_PARM_FILE contains:"
#more $LSB_SUB_PARM_FILE
#echo "LSB_SUB_MODIFY_FILE contains:"
#more $LSB_SUB_MODIFY_FILE
