#!/bin/sh

taskstarter=TaskStarter

nodes=0
for host in $LSB_HOSTS
do
    nodes=`expr $nodes + 1`
done

if [ x$nodes == x0 ];then
  echo LSB_HOSTS not set. Please start with bsub
  exit 1
fi


if [ x${1%$taskstarter} == x${1} ];then
    #start without taskstarter
    echo start $* -np $nodes
#    echo Start without starter
    $* -np $nodes
   exit
else
    #start with taskstarter
#    echo Start with starter
    echo taskstart $* -np $nodes
    taskstarter=$1
    taskstarterarg=$2
    export PSI_RARG_PRE_0=$taskstarter
    export PSI_RARG_PRE_1=$taskstarterarg
    $* -np $nodes
fi
