#!/usr/bin/env python
#
#               ParaStation psmom test suite
#
# Copyright (C) 2011 ParTec Cluster Competence Center GmbH, Munich
#
# author
# Michael Rauh (rauh@par-tec.com)
#

import sys
import os

sys.path.append(os.getenv("RTH"))
from rth import *

r = rth()
ofile = os.getenv("OUTPUT_FILE")

rth.parseOutput(r, ofile)

rth.testEnv(r, "NICE", "10")
rth.testEnv(r, "RLIMIT_CPU", "1000")
rth.testEnv(r, "RLIMIT_FSIZE", "102400")
rth.testEnv(r, "RLIMIT_DATA", "102400")
rth.testEnv(r, "RLIMIT_PMEM", "102400")
rth.testEnv(r, "RLIMIT_VMEM", "102400")
