#! /usr/bin/env bash
shopt -s nullglob

usage() {
    BASENAME=$(basename "$0")
    echo "usage: $BASENAME DIRECTORY"
}

if [[ $# -ne 1 || ! -d "$1" ]]; then
    usage
    exit 1
fi

for file in "$1"/*; do
    [[ -f $file ]] && command . "$file"
done
