#! /usr/bin/env bash
#
# ParaStation
#
# Copyright (C) 2025 ParTec AG, Munich
#
# This file may be distributed under the terms of the Q Public License
# as defined in the file LICENSE.QPL included in the packaging of this
# file.
#
# Usage: exec_all <directory>
#
# Source all regular files in the directory given as the single
# argument that match the pattern [^.]*.sh, i.e. that are not hidden
# and end with ".sh" and thus are assumed to contain shell syntax.

shopt -s nullglob

usage() {
    BASENAME=$(basename "$0")
    echo "usage: $BASENAME DIRECTORY"
}

if [[ $# -ne 1 || ! -d "$1" ]]; then
    usage
    exit 1
fi

for file in "$1"/[^.]*.sh; do
    [[ -f $file ]] && command . "$file"
done
