#!/bin/sh

# Sep 2000 Jens Hauke

rawfile=""
outfile=""
gendat="/tools/myrinet/bin/gendat"
arrayname=""
infile=""
description=""
date=`date +"%b %e %Y %T"`

while [ "$#" != "0" ]
do
    case $1 in
    -g) shift 1
	gendat="$1"
        ;;
    -o) shift 1
        outfile="$1"
        ;;
    -d) shift 1
        description="$1"
        ;;
    -a) shift 1
        arrayname="$1"
	;;
    -*) 
cat <<EOF
$0 [-g gendatpath] [-o output] [-d Description ] [-a arrayname] input
EOF
    exit 1
        ;;
    *)  infile="$1"
    esac
    shift 1
done

if [ "$outfile" = "" ] ;then   outfile="$infile".h;fi
if [ "$arrayname" = "" ] ;then arrayname="$infile";fi

#echo "$gendat --format=zlib-array --array-name=$arrayname $infile > $outfile"
echo "Date       :$date"
echo "gendat     :$gendat"
echo "Arrayname  :$arrayname"
echo "Description:$description"
echo "output     :$outfile"

$gendat --format=zlib-array --array-name=$arrayname $infile > $outfile

cat >>$outfile <<EOF
#ifndef MCPDESCINFO
#define MCPDESCINFO
typedef struct {
    char * name;
    char * description;
    char * date;
}mcp_description;
#endif

const mcp_description ${arrayname}_description = {
    "$arrayname",
    "$description",
    "$date"};
EOF




















