#! /bin/sh

SELF=$0
PSMSTART=$(dirname $SELF)/psmstart

#############

if test -z "$MPID_PSP_CMDLINE"; then
    # First Prozess. Start java with psmstart

    PARAM_COMMAND=""
    PARAM_NP="1"
    while test $# -gt 0; do
        case "$1" in
        -np|--np)	# ToDo: Dont eat ALL -np parameter
            PARAM_NP="$2"
            shift
            ;;
        *)      # ToDo: Quote $1
            PARAM_COMMAND="$PARAM_COMMAND $1"
	    ;;
        esac
        shift
    done

    export MPID_PSP_NP="$PARAM_NP"
    export MPID_PSP_CMDLINE="$PARAM_COMMAND"
    export PSI_RARG_PRE_0="$SELF"
    export PSI_EXPORTS="$PSI_EXPORTS,PSI_RARG_PRE_0,MPID_PSP_NP,MPID_PSP_CMDLINE"

#    echo "exec $PSMSTART -np $PARAM_NP $SELF"
    exec $PSMSTART -np $PARAM_NP $SELF
    echo "exec $PSMSTART -np $PARAM_NP $SELF failed!"
    exit 1
else
    # Rank 0 - (np-1) Start java from MPID_PSP_CMDLINE
#    echo "exec $MPID_PSP_CMDLINE"
    exec $MPID_PSP_CMDLINE
    echo "exec $MPID_PSP_CMDLINE failed!"
    exit 1
fi
