#!/bin/sh
# 
# PSM Myrinet Device Driver for Parastation3
#
# Script to load/unload the module and configure the interface
#
# Author: Jens Hauke <hauke@par-tec.com>, Norbert Eicker <eicker@par-tec.com>
#
# $Id: parastation,v 1.8 2003/04/03 15:49:34 eicker Exp $
#

MODULEFULLNAME=$PS_MODULE
if [ ! -f $MODULEFULLNAME ]; then
    MODULEFULLNAME=`dirname $0`/modules/$PS_MODULE
fi
if [ ! -f $PS_ROUTEFILE ]; then
    PS_ROUTEFILE=`dirname $0`/../config/$PS_ROUTEFILE
fi
MODULENAME=`basename $MODULEFULLNAME .o`
PSCONFIG=`dirname $0`/psconfig

# PSN Network Device for Parastation3
PSNINOUT=`dirname $0`/psninout
PSN_MODULENAME=`dirname $PS_MODULE`/mod_psn.o

case "$1" in
    start)
	# Test if module is already loaded
	#
	modules=`lsmod | tail +2 | colrm 20`
	found=0
	for mod in $modules; do
	    if [ $mod == $MODULENAME ]; then
		found=1;
	    fi
	done
	unset modules mod

	if [ $found == 0 ] ; then
	    insmod -f "$MODULEFULLNAME" > /dev/null 2>&1
            if [ $? -ne 0 ]
            then
                  echo "Failed to configure subsystem: " $MODULEFULLNAME
		  exit 1
            fi
        fi
	$PSCONFIG -key "$PS_LIC" || exit 2
	$PSCONFIG -id "$PS_ID" "$PS_ROUTEFILE" || exit 3

# The following two lines increase somtimes the performance of huge applications
#	$PSCONFIG -p 4 1
#	$PSCONFIG -p 5 0

# Enable the next line to load the PSN Network Device for Parastation
#	$PSNINOUT -m $PSN_MODULENAME -n "192.168.48.0" -p 20
	
	;;

    stop)
	$PSNINOUT -m $PSN_MODULENAME -o
	rmmod "$MODULENAME"
	;;


    *)
	echo "Usage: $0 {start|stop}"
	exit 1
	;;
esac


