#!/bin/sh


MODULENAME=psmx
PSCONFIG=`dirname $0`/psconfig


case "$1" in
    start)
	CONFIGURED=`sysconfig -s $MODULENAME | grep -w configured`
        if [ "$CONFIGURED" = "" ] ; then
	    sysconfig -c "$MODULENAME"
            if [ $? -ne 0 ]
            then
                  echo "Failed to configure subsystem: " $MODULENAME
		  exit 1
            fi
        fi
	$PSCONFIG -key "$PS_LIC" || exit 2
	$PSCONFIG -id "$PS_ID" "$PS_ROUTEFILE" || exit 3
	
	;;

    stop)
	sysconfig -u "$MODULENAME"
	;;


    *)
	echo "Usage: $0 {start|stop}"
	exit 1
	;;
esac


