#!/bin/sh


MODULEFULLNAME=$PS_MODULE
MODULENAME=`basename $MODULEFULLNAME .o`
PSCONFIG=`dirname $0`/psconfig

case "$1" in
    start)
	# Test if module is already loaded
	#
	modules=`lsmod | tail +2 | colrm 20`
	found=0
	for mod in $modules; do
	    if [ $mod == $MODULENAME ]; then
		found=1;
	    fi
	done
	unset modules mod

	if [ $found == 0 ] ; then
	    insmod "$MODULEFULLNAME"
            if [ $? -ne 0 ]
            then
                  echo "Failed to configure subsystem: " $MODULEFULLNAME
		  exit 1
            fi
        fi
	$PSCONFIG -key "$PS_LIC" || exit 2
	$PSCONFIG -id "$PS_ID" "$PS_ROUTEFILE" || exit 3
	
	;;

    stop)
	rmmod "$MODULENAME"
	;;


    *)
	echo "Usage: $0 {start|stop}"
	exit 1
	;;
esac


