#!/bin/sh
# 
# Pseudo hardware-type skript to start the psaccounter.
#
# Author: Michael Rauh <rauh@par-tec.com>
#
# $Id$
#

case "$1" in
    start)
        su -s "/bin/sh" -c "/opt/parastation/bin/psaccounter -p gzip -e" nobody
	;;

    stop)
        killall psaccounter 2>&1 1>/dev/null	
	;;

    statusheader)
	;;

    status)
	;;

    *)
	echo "Usage: $0 {start|stop|statusheader|status}"
	exit 1
	;;
esac

exit 0
