#!/bin/sh
# 
# Script to get some infiniband statistics
#
# Author: Jens eicker <eicker@par-tec.com>
#
# $Id: ps_ib,v 1.1 2004/05/25 11:27:29 eicker Exp $
#

case "$1" in
    start)
	modprobe mod_vapi
	;;
    stop)
	;;
    statusheader)
	# No Header
	/bin/echo -n ' '
	;;

    status)
	echo
	cat /proc/infiniband/core/ca1/port1/counters
	;;

    *)
	echo "Usage: $0 {start|stop|statusheader|status}"
	exit 1
	;;
esac

