#!/bin/bash
#
# ParaStation
#
# Copyright (C) 2010 ParTec Cluster Competence Center GmbH, Munich
#
# This file may be distributed under the terms of the Q Public License
# as defined in the file LICENSE.QPL included in the packaging of this
# file.
#
# Authors:      Jens Hauke <hauke@par-tec.com>
#
# Translate the ParaStation up/down status of all nodes to a cmu
# usable status file. (Alternativ for the cmustatus service)
# 
# This script could be triggerd by psid:
#
# /etc/parastation.conf:
# nodeUpScript  "/opt/parastation/scripts/psid2cmustatus"
# nodeDownScript "/opt/parastation/scripts/psid2cmustatus"
#

cmu_statfile="${1-/opt/cmu/log/cmustatus.log}"

/opt/parastation/bin/psiadmin -c "resolve;status" | gawk '
$1==0	{ sec++ }

sec==1	{ nname[$1] = $2 }
sec==2	{ print nname[$1], $2=="up" ? "1" : "0"}
' > "$cmu_statfile"

# Local Variables:
#  compile-command: "./psid2cmustatus /dev/stdout"
# End:
