#!/bin/sh 
#***********************************************************
#*                  ParaStation
#*
#*       Copyright (c) 2002 ParTec AG Karlsruhe
#*       All rights reserved.
#***********************************************************/
#**
#* PSM_INSTALL: ParaStation De-/Installationscript
#*
#* $Id$
#*
#* @author  
#*         Eduard Syrchyn <syrchyn@par-tec.de>
#*         Jens Hauke <hauke@par-tec.de>
#*


#Global variables
UNAME=`uname`
ETC_DIR="/etc"

_tmp=`dirname $0`
SELFPATH=`cd $_tmp;pwd`

PSCNFDIR=$SELFPATH
PSMAIN=`cd $PSCNFDIR/..;pwd`

#Linux only

#/etc/inetd.conf
INETD_PSIDMASK="^[ 	]*psid[ 	]"
INETD_PSIDLINE="psid	stream	tcp	nowait	root	$PSMAIN/bin/psid psid"
INETD_PID="/var/run/inetd.pid"
INETD_CNF="$ETC_DIR/inetd.conf"
INETD_BKP="$INETD_CNF.psm"

#/etc/xinetd.d
XINETD_DIR="$ETC_DIR/xinetd.d"
XINETD_PID="/var/run/xinetd.pid"
XINETD_PARA="\
#
# parastation
#
service psid
{
        disable = no
        socket_type     = stream
        wait            = no
        user            = root
        server          = $PSMAIN/bin/psid
        log_on_failure  += USERID
}
"
XINETD_PSM="$ETC_DIR/xinetd.d/parastation"

#/etc/services
SERV_PSIDMASK="^[ 	]*psid[ 	]"
SERV_PSIDLINE="psid             888/tcp       # ParaStation Daemon Start Port"
SERV_CNF="$ETC_DIR/services"
SERV_BKP="$SERV_CNF.psm"

self_post_inst_msg() {
    echo "#################################################################"
    echo "  Please, prepare and mantain the file                           "
    echo "  $PSCNFDIR/parastation.conf! (s.o. parastation.conf.template) "
    echo "#################################################################"
}

symlink() {
    ln -s -f $1 $2
    if [ $? -gt 0 ]
    then
	echo "WARNING:  cannot create the symbolic link $1 -> $2!"
    fi
}

backup() {
    src=$1
    bak=$2
    if [ ! -f $bak ]
    then
	cp $src $bak
	if [ $? -gt 0 ]
	then
	    echo "Create backupfile $bak faild. Abort!"
	    exit 1
	fi
    fi
}

# Remove backup, if backup equals orginal
unbackup() {
    src=$1
    bak=$2
    if [ -f $bak ]
    then
	diff -bB $src $bak
	if [ $? -eq 0 ]
	then
	    rm $bak
	fi
    fi
}

patch_conf() {
    conf="$1"
    mask="$2"
    line="$3"

    oldline=`grep "$mask" $conf`
    if [ $? -eq 0 ]
    then
	if [ "$oldline"x != "$line"x ]
	then
	    echo "Line        $oldline"
	    echo "should be   $line"
	else
	    echo "Unchanged   $line"
	fi
	return 0
    fi
	    echo "Append      $line"
    echo "$line" >> $conf
}

unpatch_conf() {
    conf="$1"
    mask="$2"
    line="$3"

    oldline=`grep "$mask" $conf`
    if [ $? -eq 0 ]
    then
	if [ "$oldline"x != "$line"x ]
	then
	    echo "Unchanged   $oldline"
	else
	    echo "Remove      $line"
	    ed $conf >&/dev/null <<EOF
,g@^$line\$@d
w
q
EOF
	fi
	return 0
    fi
	    echo "Cant find   $line"
}

reload_inetd() {        
    if [ -f $INETD_PID ]    
    then
	echo "Reload inetd."
 	sss=`cat $INETD_PID`
	kill -s HUP $sss    
    else 
	echo "#######################################################"
	echo "# Reload or start the inetd (/usr/bin/inetd) daemon ! #"
	echo "#######################################################"
    fi
}

reload_xinetd() {        
    if [ -f $XINETD_PID ]    
    then
	echo "Reload xinetd."
 	sss=`cat $XINETD_PID`
	kill -s HUP $sss    
    else 
	echo "#######################################################"
	echo "# Reload or start the xinetd daemon !                 #"
	echo "#######################################################"
    fi
}

patch_services() {
    backup $SERV_CNF $SERV_BKP
    echo "Update $SERV_CNF."
    patch_conf "$SERV_CNF" "$SERV_PSIDMASK" "$SERV_PSIDLINE"
}

patch_inetd() {
    backup $INETD_CNF $INETD_BKP
    echo "Update $INETD_CNF."
    patch_conf "$INETD_CNF" "$INETD_PSIDMASK" "$INETD_PSIDLINE"
    reload_inetd
}

patch_xinetd() {
    echo "Update $XINETD_DIR."
    echo "$XINETD_PARA" > $XINETD_PSM
    reload_xinetd
}

cleanup_services() {
    unpatch_conf "$SERV_CNF" "$SERV_PSIDMASK" "$SERV_PSIDLINE"
    unbackup $SERV_CNF $SERV_BKP
}

cleanup_inetd() {
    unpatch_conf "$INETD_CNF" "$INETD_PSIDMASK" "$INETD_PSIDLINE"
    unbackup $INETD_CNF $INETD_BKP
    reload_inetd
}

cleanup_xinetd() {
    if [ -f $XINETD_PSM ]
    then
	rm $XINETD_PSM
    fi
    reload_xinetd
}

self_check_root() {
    WHO=`whoami`
    if [ $WHO != "root" ]
    then
	echo "You should be <root>, but you are <$WHO>!"
    fi
}

create_devicefiles() {
   mknod /dev/psm c 40 0
   chmod 666 /dev/psm
}

cleanup_devicefiles() {
   rm /dev/psm
}

create_configlink() {
   ln -s $PSMAIN/config/parastation.conf $ETC_DIR/parastation.conf
}

cleanup_configlink() {
    if [ -L $ETC_DIR/parastation.conf ]
    then
	rm -f $ETC_DIR/parastation.conf
    fi
}

do_install() {
    echo "Install ParaStation in $PSMAIN"

    patch_services
    if [ -f $INETD_CNF ]
    then
	patch_inetd
    fi
    if [ -d $XINETD_DIR ]
    then
	patch_xinetd
    fi
    create_devicefiles
    create_configlink
}

do_uninstall() {
    echo "Uninstall ParaStation from $PSMAIN"
    killall psid
    cleanup_services
    if [ -f $INETD_CNF ]
    then
	cleanup_inetd
    fi
    if [ -d $XINETD_DIR ]
    then
	cleanup_xinetd
    fi
    cleanup_devicefiles
    cleanup_configlink
}

do_help() {
    echo "Use: $0 [-i|-U|-h]"
    echo "-i       : install"
    echo "-U       : uninstall "
    echo "-h       : this poor help..."
}

#If sysconfig fails, try this and watch the console
#/sbin/sysconfig -v -c $PSMDRV

#To unload the driver
#/sbin/sysconfig -u $PSMDRV

#to delete the entry
#/sbin/sysconfigdb -d $PSMDRV

if [ "$UNAME" = "Linux" ]
then
    echo
else
    echo "###################################"
    echo "# ATTENTION! Unknown OS ($UNAME)! #"
    echo "###################################"
fi

self_check_root

case "$1" in
    -i)
	do_install
	self_post_inst_msg
	;;
    -U)
	do_uninstall
	;;
    -u)
	;;
    -h)
	do_help
	;;
    *)
	do_help
	exit 1
esac
