#!/bin/sh

DVER=${1-"x.x.x"}
BUILDDIR=`pwd`
BINDIR=$BUILDDIR/opt/parastation

SPECFILE=psfe-$DVER.spec

mkdir -p .build
ln -sf "../opt" ".build/opt"
if [ -f /usr/bin/rpmbuild ] ; then
    RPM=/usr/bin/rpmbuild
else
    RPM=rpm
fi

cat > $SPECFILE <<EOF
Summary:   ParaStation FE Cluster Communication libraries
Vendor:    ParTec AG, Karlsruhe, Germany
Name:      psfe
Version:   $DVER
Release:   `date +%Y%m%d`
Copyright: (c) 2001-2003 ParTec AG
Group:     System/Development/Libraries
Packager:  support@par-tec.de
Requires:  psmgmt
BuildRoot: $BUILDDIR/.build
 
%description
ParaStation FE Cluster Communication libraries. TCP/IP Version.

%post
%preun
%files
%attr(-,root,root) /opt/parastation
EOF

$RPM -v -bb $SPECFILE 2>&1 |while read tag val
do
    echo $tag $val
    if [ x$tag = xWrote: ];then
	echo Moving $val to $BUILDDIR
	mv $val $BUILDDIR
    fi
done
