#!/bin/sh

DVER=${1-"x.x.x"}
BUILDDIR=`pwd`
BINDIR=$BUILDDIR/opt/parastation

SPECFILE=psmgmt-$DVER.spec

if [ -f /usr/bin/rpmbuild ] ; then
    RPM=/usr/bin/rpmbuild
else
    RPM=rpm
fi

cat > $SPECFILE <<EOF
Summary:   ParaStation Management
Vendor:    ParTec AG, Karlsruhe, Germany
Name:      psmgmt
Version:   $DVER
Release:   `date +%Y%m%d`
Copyright: (c) 2001-2003 ParTec AG
Group:     System/Development/Libraries
Packager:  support@par-tec.de

BuildRoot: $BUILDDIR/build
 
%description
ParaStation Management Layer.

%pre
    if [ "\$1" = "2" ] ; then  # Thats an update
      if [ -x /opt/parastation/config/PSM_INSTALL ]; then
        # Call the OLD uninstall script.
        /opt/parastation/config/PSM_INSTALL -U
      fi
    fi
%post
    /opt/parastation/config/PSM_INSTALL -i
%preun
    if [ "\$1" = "0" ] ; then  # Thats NOT an update
      # Call the uninstall script only, if this is NOT an update.
      /opt/parastation/config/PSM_INSTALL -U
    fi
%files
%attr(-,root,root) /opt/parastation
EOF

$RPM -v -bb $SPECFILE 2>&1 |while read tag val
do
    echo $tag $val
    if [ x$tag = xWrote: ];then
	echo Moving $val to $BUILDDIR
	mv $val $BUILDDIR
    fi
done
