#!/bin/sh

DVER=${1-"x.x.x"}
BUILDDIR=`pwd`
BINDIR=$BUILDDIR/opt/parastation

SPECFILE=ps3ibis-$DVER.spec

cat > $SPECFILE <<EOF
Summary:   ParaStation 3 IBIS Cluster Communication and Management
Vendor:    ParTec AG, Karlsruhe, Germany
Name:      ps3ibis
Version:   $DVER
Release:   `date +%Y%m%d`
Copyright: (c) 2001-2003 ParTec AG
Group:     System/Development/Libraries
Packager:  support@par-tec.de

BuildRoot: $BUILDDIR
 
%description
ParaStation 3 IBIS Cluster Communication and Management. TCP/IP Version.

%post
    /opt/parastation/config/PSM_INSTALL -i
%preun
    /opt/parastation/config/PSM_INSTALL -u
%files
%attr(-,root,root) /opt/parastation
EOF

rpm -v -bb $SPECFILE 2>&1 |while read tag val
do
    echo $tag $val
    if [ x$tag = xWrote: ];then
	echo Moving $val to $BUILDDIR
	mv $val $BUILDDIR
    fi
done
