#!/bin/sh

DVER=${1-"x.x.x"}
BUILDDIR=`pwd`
BINDIR=$BUILDDIR/opt/parastation

SPECFILE=psm-$DVER.spec

cat > $SPECFILE <<EOF
Summary:   ParaStation Cluster Communication and Management
Vendor:    ParTec AG, Munich, Germany
Name:      psm
Version:   $DVER
Release:   `date +%Y%m%d`.`uname`
Copyright: (c) 2001-2002 ParTec AG
Group:     System/Development/Libraries
Packager:  support@par-tec.de

BuildRoot: $BUILDDIR

%package doc
Summary:   ParaStation Cluster Communication and Management Documentation
Group:     System/Development/Libraries
 
%description
ParaStation Cluster Communication and Management

%description doc
The ParaStation Documentation


%post
    /opt/parastation/config/PSM_INSTALL -i
%preun
    /opt/parastation/config/PSM_INSTALL -u
%files
%dir %attr(-,root,root) /opt/parastation
%attr(-,root,root) /opt/parastation/INSTALL
%attr(-,root,root) /opt/parastation/VERSION
%attr(-,root,root) /opt/parastation/bin
%attr(-,root,root) /opt/parastation/config
%attr(-,root,root) /opt/parastation/include
%attr(-,root,root) /opt/parastation/lib

%files doc
%dir %attr(-,root,root) /opt/parastation
%attr(-,root,root) /opt/parastation/doc
%attr(-,root,root) /opt/parastation/man
EOF

rpm -v -bb $SPECFILE 2>&1 |while read tag val
do
    echo $tag $val
    if [ x$tag = xWrote: ];then
	echo Moving $val to $BUILDDIR
	mv $val $BUILDDIR
    fi
done
