#include <linux/version.h>
#include <linux/config.h>

#ifdef CONFIG_SMP
MODULE_CONFIG_SMP=1
#else
MODULE_CONFIG_SMP=0
#endif

#ifdef CONFIG_HIGHMEM
MODULE_CONFIG_HIGHMEM=1
#else
MODULE_CONFIG_HIGHMEM=0
#endif

#ifdef CONFIG_HIGHMEM4G
MODULE_CONFIG_HIGHMEM4G=1
#else
MODULE_CONFIG_HIGHMEM4G=0
#endif

#ifdef CONFIG_HIGHMEM64G
MODULE_CONFIG_HIGHMEM64G=1
#else
MODULE_CONFIG_HIGHMEM64G=0
#endif

MODULE_UTS_RELEASE=UTS_RELEASE

